apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: katf4uy3z-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe:2bd11d7799d79ea590484ccecd86375bf213839c@sha256:b85a03a85d14e7ee5a52de73551359e2364461517aab4d94dd9f27c5033303ee
        name: container-image  
